basePath: /e-commerce
definitions:
  admin.NewDataNoID:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      email:
        type: string
      full_name:
        type: string
      image:
        items:
          type: string
        type: array
      password:
        type: string
      phone_number:
        type: string
      postal_code:
        type: string
      role:
        type: string
      state:
        type: string
      username:
        type: string
    type: object
  admin.NewDataResp:
    properties:
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      image:
        items:
          type: string
        type: array
      password:
        type: string
      phone_number:
        type: string
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  admin.NewUser:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  admin.NewUserResp:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  admin.UserDetails:
    properties:
      country:
        type: string
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  admin.UserInfo:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      image:
        items:
          type: string
        type: array
      password:
        type: string
      phone_number:
        type: string
      postal_code:
        type: string
      role:
        type: string
      state:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  admin.Users:
    properties:
      limit:
        type: integer
      page:
        type: integer
      users:
        items:
          $ref: '#/definitions/admin.UserDetails'
        type: array
    type: object
  basket.Id:
    properties:
      product_id:
        type: string
    type: object
  basket.NewProduct:
    properties:
      product_id:
        type: string
      quantity:
        type: integer
    type: object
  basket.Product:
    properties:
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  basket.Products:
    properties:
      items:
        items:
          $ref: '#/definitions/basket.Product'
        type: array
    type: object
  basket.Quantity:
    properties:
      product_id:
        type: string
      quantity:
        type: integer
    type: object
  product.Discount:
    properties:
      discount_price:
        type: number
      status:
        type: boolean
    type: object
  product.Image:
    properties:
      image_url:
        type: string
    type: object
  product.InsertResp:
    properties:
      created_at:
        type: string
      id:
        type: string
    type: object
  product.NewDataNoId:
    properties:
      category:
        type: string
      description:
        type: string
      discount:
        $ref: '#/definitions/product.Discount'
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  product.NewProduct:
    properties:
      category:
        type: string
      description:
        type: string
      discount:
        $ref: '#/definitions/product.Discount'
      images:
        items:
          $ref: '#/definitions/product.Image'
        type: array
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  product.ProductInfo:
    properties:
      category:
        type: string
      comment_count:
        type: integer
      created_at:
        type: string
      description:
        type: string
      discount:
        $ref: '#/definitions/product.Discount'
      id:
        type: string
      images:
        items:
          $ref: '#/definitions/product.Image'
        type: array
      name:
        type: string
      price:
        type: number
      purchase_count:
        type: integer
      rating:
        type: number
      stock:
        type: integer
    type: object
  product.Products:
    properties:
      limit:
        type: integer
      page:
        type: integer
      products:
        items:
          $ref: '#/definitions/product.ProductInfo'
        type: array
    type: object
  product.UpdateResp:
    properties:
      id:
        type: string
      updated_at:
        type: string
    type: object
  user.NewData:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      email:
        type: string
      full_name:
        type: string
      image:
        items:
          type: string
        type: array
      password:
        type: string
      phone_number:
        type: string
      postal_code:
        type: string
      state:
        type: string
      username:
        type: string
    type: object
  user.Profile:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      image:
        items:
          type: string
        type: array
      phone_number:
        type: string
      postal_code:
        type: string
      role:
        type: string
      state:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  user.UpdateResp:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      image:
        items:
          type: string
        type: array
      phone_number:
        type: string
      postal_code:
        type: string
      role:
        type: string
      state:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Gateway of E-Commerce
  title: E-Commerce
  version: "1.0"
paths:
  /admin/product:
    post:
      description: Adds new product
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.NewProduct'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.InsertResp'
        "400":
          description: Invalid data provided
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Creates a product
      tags:
      - product
  /admin/product/{id}:
    delete:
      description: Deletes product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Product deleted successfully
          schema:
            type: string
        "400":
          description: Invalid data provided
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Deletes product
      tags:
      - product
    get:
      description: Retrieves product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ProductInfo'
        "400":
          description: Invalid data provided
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Gets product
      tags:
      - product
    put:
      description: Updates product info
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.NewDataNoId'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.UpdateResp'
        "400":
          description: Invalid data provided
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Updates product
      tags:
      - product
  /admin/product/all:
    get:
      description: Retrieves products
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: Category
        in: query
        name: category
        type: string
      - description: Comment count
        in: query
        name: comment_count
        type: integer
      - description: Rating
        in: query
        name: rating
        type: number
      - description: Sort by
        in: query
        name: sort_by
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.Products'
        "400":
          description: Invalid pagination parameters
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Gets products
      tags:
      - product
  /admin/user:
    post:
      description: Adds a new user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/admin.NewUser'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.NewUserResp'
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Adds user
      tags:
      - admin
  /admin/user/{id}:
    delete:
      description: Deletes user info by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: User deleted successfully
          schema:
            type: string
        "400":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Deletes user
      tags:
      - admin
    get:
      description: Retrieves user info by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.UserInfo'
        "400":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Gets user
      tags:
      - admin
    put:
      description: Updates user info by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: New user data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/admin.NewDataNoID'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.NewDataResp'
        "400":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Updates user
      tags:
      - admin
  /admin/users:
    get:
      description: Retrieves users from the database by filtering
      parameters:
      - description: Full name
        in: query
        name: full_name
        type: string
      - description: Location
        in: query
        name: location
        type: string
      - description: Role
        in: query
        name: role
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of users per page
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.Users'
        "400":
          description: Invalid pagination parameters
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Fetches users
      tags:
      - admin
  /user/{id}:
    delete:
      description: Deletes user info by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: User deleted successfully
          schema:
            type: string
        "400":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Deletes user
      tags:
      - user
    get:
      description: Retrieves user profile by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.Profile'
        "400":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Gets user
      tags:
      - user
    put:
      description: Updates user info by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: New user data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.NewData'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UpdateResp'
        "400":
          description: Invalid user id or data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Updates user
      tags:
      - user
  /user/basket:
    delete:
      description: Removes product from basket
      parameters:
      - description: Product ID
        in: body
        name: product_id
        required: true
        schema:
          $ref: '#/definitions/basket.Id'
      responses:
        "200":
          description: Product removed from basket successfully
          schema:
            type: string
        "400":
          description: Invalid data provided
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Removes product from basket
      tags:
      - basket
    get:
      description: Retrieves basket
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/basket.Products'
        "400":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Gets basket
      tags:
      - basket
    post:
      description: Adds product to basket
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/basket.NewProduct'
      responses:
        "200":
          description: Product added to basket successfully
          schema:
            type: string
        "400":
          description: Invalid data provided
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Adds product
      tags:
      - basket
    put:
      description: Updates quantity of product in basket
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/basket.Quantity'
      responses:
        "200":
          description: Basket updated successfully
          schema:
            type: string
        "400":
          description: Invalid data provided
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Updates basket
      tags:
      - basket
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
