// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: translate.proto

package translate_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Uzbek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *Uzbek) Reset() {
	*x = Uzbek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uzbek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uzbek) ProtoMessage() {}

func (x *Uzbek) ProtoReflect() protoreflect.Message {
	mi := &file_translate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uzbek.ProtoReflect.Descriptor instead.
func (*Uzbek) Descriptor() ([]byte, []int) {
	return file_translate_proto_rawDescGZIP(), []int{0}
}

func (x *Uzbek) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

type English struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *English) Reset() {
	*x = English{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *English) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*English) ProtoMessage() {}

func (x *English) ProtoReflect() protoreflect.Message {
	mi := &file_translate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use English.ProtoReflect.Descriptor instead.
func (*English) Descriptor() ([]byte, []int) {
	return file_translate_proto_rawDescGZIP(), []int{1}
}

func (x *English) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_translate_proto protoreflect.FileDescriptor

var file_translate_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x55, 0x7a, 0x62, 0x65, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0x1f, 0x0a, 0x07, 0x45, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x32, 0x4f, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x41, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x7a, 0x62, 0x65, 0x6b, 0x1a, 0x1a, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6e,
	0x67, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x23, 0x5a, 0x21, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_translate_proto_rawDescOnce sync.Once
	file_translate_proto_rawDescData = file_translate_proto_rawDesc
)

func file_translate_proto_rawDescGZIP() []byte {
	file_translate_proto_rawDescOnce.Do(func() {
		file_translate_proto_rawDescData = protoimpl.X.CompressGZIP(file_translate_proto_rawDescData)
	})
	return file_translate_proto_rawDescData
}

var file_translate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_translate_proto_goTypes = []interface{}{
	(*Uzbek)(nil),   // 0: translate_service.Uzbek
	(*English)(nil), // 1: translate_service.English
}
var file_translate_proto_depIdxs = []int32{
	0, // 0: translate_service.Translator.Translate:input_type -> translate_service.Uzbek
	1, // 1: translate_service.Translator.Translate:output_type -> translate_service.English
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_translate_proto_init() }
func file_translate_proto_init() {
	if File_translate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_translate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uzbek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*English); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_translate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translate_proto_goTypes,
		DependencyIndexes: file_translate_proto_depIdxs,
		MessageInfos:      file_translate_proto_msgTypes,
	}.Build()
	File_translate_proto = out.File
	file_translate_proto_rawDesc = nil
	file_translate_proto_goTypes = nil
	file_translate_proto_depIdxs = nil
}
